// Zusatz-Ort (Kapitel 1 und Ehrengarde): die Zwergenmine hinter dem Dorf
// Bergmann Dori braucht Licht, Bergfrau Gimla füllt die Lore mit Kristallen, Lehrling Nori hat Hunger
export default {
  name: 'Die Zwergenmine',
  musik: 'hoehle',
  dunkel: 0.55,
  heldLicht: 70,
  hintergrund: '#07040c',
  grundBoden: 'hoehle',
  karte: [
    'ÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖ',
    'Öϑ;;;;ψ;;;;ϑ;;ψψ;;;;ϑÖ',
    'Ö+;;;;;;;;;+;;;;;;;;+Ö',
    'Ö;;;(;;;;;;;;;;;;g;;;Ö',
    'Öρρρρρλ+ρρρρρρρρρρρρ;Ö',
    'Ö;;;;;;;;;;;;;;;;;;;;Ö',
    'Ö;;d;;;;;;K;;;;;;;n;)Ö',
    'Ö;;;;;;;;;;;;;;;;;;;;Ö',
    'Ö$;;;;;!;;;;;;;!;;;;KÖ',
    'ÖÖÖÖÖÖÖÖÖÖ;;ÖÖÖÖÖÖÖÖÖÖ',
    'ÖÖÖÖÖÖÖÖÖÖ1ÖÖÖÖÖÖÖÖÖÖÖ',
  ],
  ausgaenge: {
    1: { karte: 'dorf', ziel: 6, aussehen: 'weg', weiter: true },
  },
  figuren: {
    d: {
      name: 'Bergmann Dori',
      aussehen: 'dori',
      stimme: { hoehe: 0.7 },
      zusatz: true,
      wunsch: 'fackel',
      sagt: 'Huch, meine Lampe ist ausgegangen! Holst du mir eine Fackel aus der Feuerschale?',
      danke: 'Licht! Jetzt sehe ich wieder alles. Danke!',
      danach: 'In dieser Mine glitzert es überall!',
    },
    g: {
      name: 'Bergfrau Gimla',
      aussehen: 'gimla',
      stimme: { hoehe: 1.05 },
      zusatz: true,
      wunsch: 'kristall',
      anzahl: 3,
      sagt: 'Die Lore soll voll werden! Bringst du mir drei Kristalle? Sie leuchten an der Wand.',
      weiter: 'Funkel, funkel! Noch {rest}!',
      danke: 'Die Lore ist voll! Was für ein Schatz!',
      danach: 'Diese Kristalle bringen wir der Königin.',
    },
    n: {
      name: 'Lehrling Nori',
      aussehen: 'nori',
      stimme: { hoehe: 1.7, tempo: 1.05 },
      zusatz: true,
      wunsch: 'pilze',
      sagt: 'Mein Bauch knurrt! Dort hinten wachsen leuchtende Pilze. Bringst du mir welche?',
      danke: 'Lecker! Jetzt habe ich wieder Kraft zum Graben.',
      danach: 'Wenn ich gross bin, werde ich der beste Bergmann!',
    },
  },
};
